# Generated by Django 5.1.5 on 2025-01-18 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snipept',
            new_name='Snippet',
        ),
    ]
