# Generated by Django 5.1.5 on 2025-01-18 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_rename_snipept_snippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snippet',
            old_name='lineonos',
            new_name='linenos',
        ),
    ]
